"""Imports known to succeed on every CPython of a given minor or later.

The table backs one lexical shape, the import fallback (design §11.1):

.. code-block:: python

    try:
        import threading
    except ImportError:
        import dummy_threading as threading

When every name the ``try`` body imports is listed here with a first version
at or below a target minor, the ``except ImportError`` handler cannot run on
that target and is treated as unreachable there. A name that is not listed
keeps the handler reachable; nothing is inferred from an import the table
does not know.

An entry is a dotted name and the first minor on which the import succeeds.
``"a.b"`` covers ``import a.b`` and ``from a import b``, whether ``b`` is a
submodule or an attribute; ``import a`` needs its own entry. The criteria for
listing are deliberately narrow:

- present on every platform CPython supports, so no ``winreg``, ``fcntl``,
  ``pwd``, ``termios`` or ``resource``;
- built into every CPython, so no module a distribution may split out or a
  build may lack: ``ssl``, ``sqlite3``, ``bz2``, ``lzma``, ``zlib``,
  ``ctypes``, ``tkinter``, ``curses``, ``readline``, ``dbm``, ``ensurepip``,
  ``venv``, ``idlelib``, ``turtle``;
- never removed, and not the subject of a registry rule: a fallback around a
  module that has since gone is exactly the case the handler exists for.
  ``tests/unit/test_known_imports.py`` pins that disjointness;
- attributes are listed when they are the replacement a fallback exists for
  (``collections.abc.Mapping``, ``inspect.getfullargspec``,
  ``base64.encodebytes``) or a version-gated addition projects guard with an
  ``except ImportError`` (``typing.Literal``, ``datetime.UTC``). A ``from``
  import of an unlisted attribute is not recognised.

Versions below 3.8 are recorded as CPython documents them; the registry window
opens at 3.8, so they all read as "always".
"""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING, Final

from pyahead.versions import PythonMinor

if TYPE_CHECKING:
    from collections.abc import Mapping

_ALWAYS = "3.0"

_MODULES: dict[str, str] = dict.fromkeys(
    (
        "abc",
        "argparse",
        "array",
        "ast",
        "asyncio",
        "atexit",
        "base64",
        "bdb",
        "binascii",
        "bisect",
        "builtins",
        "cProfile",
        "calendar",
        "cmath",
        "cmd",
        "code",
        "codecs",
        "codeop",
        "collections",
        "collections.abc",
        "colorsys",
        "compileall",
        "concurrent",
        "concurrent.futures",
        "configparser",
        "contextlib",
        "contextvars",
        "copy",
        "copyreg",
        "csv",
        "dataclasses",
        "datetime",
        "decimal",
        "difflib",
        "dis",
        "doctest",
        "email",
        "email.message",
        "email.mime",
        "email.mime.multipart",
        "email.mime.text",
        "email.parser",
        "email.utils",
        "encodings",
        "enum",
        "errno",
        "faulthandler",
        "filecmp",
        "fileinput",
        "fnmatch",
        "fractions",
        "ftplib",
        "functools",
        "gc",
        "genericpath",
        "getopt",
        "getpass",
        "gettext",
        "glob",
        "gzip",
        "hashlib",
        "heapq",
        "hmac",
        "html",
        "html.entities",
        "html.parser",
        "http",
        "http.client",
        "http.cookiejar",
        "http.cookies",
        "http.server",
        "imaplib",
        "importlib",
        "importlib.abc",
        "importlib.machinery",
        "importlib.util",
        "inspect",
        "io",
        "ipaddress",
        "itertools",
        "json",
        "json.decoder",
        "json.encoder",
        "keyword",
        "linecache",
        "locale",
        "logging",
        "logging.config",
        "logging.handlers",
        "mailbox",
        "marshal",
        "math",
        "mimetypes",
        "modulefinder",
        "multiprocessing",
        "multiprocessing.pool",
        "netrc",
        "ntpath",
        "numbers",
        "opcode",
        "operator",
        "optparse",
        "os",
        "os.path",
        "pathlib",
        "pdb",
        "pickle",
        "pickletools",
        "pkgutil",
        "platform",
        "plistlib",
        "poplib",
        "posixpath",
        "pprint",
        "profile",
        "pstats",
        "py_compile",
        "pyclbr",
        "pydoc",
        "pyexpat",
        "queue",
        "quopri",
        "random",
        "re",
        "reprlib",
        "rlcompleter",
        "runpy",
        "sched",
        "secrets",
        "select",
        "selectors",
        "shlex",
        "shutil",
        "signal",
        "site",
        "smtplib",
        "socket",
        "socketserver",
        "stat",
        "statistics",
        "string",
        "stringprep",
        "struct",
        "subprocess",
        "symtable",
        "sys",
        "sysconfig",
        "tabnanny",
        "tarfile",
        "tempfile",
        "textwrap",
        "threading",
        "time",
        "timeit",
        "token",
        "tokenize",
        "trace",
        "traceback",
        "tracemalloc",
        "types",
        "typing",
        "unicodedata",
        "unittest",
        "unittest.mock",
        "urllib",
        "urllib.error",
        "urllib.parse",
        "urllib.request",
        "urllib.response",
        "urllib.robotparser",
        "uuid",
        "warnings",
        "wave",
        "weakref",
        "webbrowser",
        "wsgiref",
        "wsgiref.simple_server",
        "wsgiref.util",
        "xml",
        "xml.dom",
        "xml.dom.minidom",
        "xml.etree",
        "xml.etree.ElementTree",
        "xml.parsers",
        "xml.parsers.expat",
        "xml.sax",
        "xml.sax.saxutils",
        "xmlrpc",
        "xmlrpc.client",
        "xmlrpc.server",
        "zipapp",
        "zipfile",
        "zipimport",
        # Built-in modules every CPython 3 provides; the private names are the
        # documented fallback partners of ``imp`` and ``thread``.
        "_imp",
        "_thread",
    ),
    _ALWAYS,
)

_LATER_MODULES: dict[str, str] = {
    "importlib.metadata": "3.8",
    "importlib.resources": "3.7",
    "importlib.resources.abc": "3.11",
    "graphlib": "3.9",
    "zoneinfo": "3.9",
    "tomllib": "3.11",
    # ``sre_constants`` and ``sre_parse`` fallbacks after these succeed.
    "re._constants": "3.11",
    "re._parser": "3.11",
    "re._compiler": "3.11",
}

_ATTRIBUTES: dict[str, str] = {
    # The ``collections`` aliases removed in 3.10 (CPY0141 to CPY0165).
    **dict.fromkeys(
        (
            "collections.abc.Hashable",
            "collections.abc.Iterable",
            "collections.abc.Iterator",
            "collections.abc.Sized",
            "collections.abc.Container",
            "collections.abc.Callable",
            "collections.abc.Set",
            "collections.abc.MutableSet",
            "collections.abc.Mapping",
            "collections.abc.MutableMapping",
            "collections.abc.MappingView",
            "collections.abc.KeysView",
            "collections.abc.ItemsView",
            "collections.abc.ValuesView",
            "collections.abc.Sequence",
            "collections.abc.MutableSequence",
        ),
        "3.3",
    ),
    "collections.abc.Awaitable": "3.5",
    "collections.abc.Coroutine": "3.5",
    "collections.abc.AsyncIterable": "3.5",
    "collections.abc.AsyncIterator": "3.5",
    "collections.abc.Generator": "3.5",
    "collections.abc.AsyncGenerator": "3.6",
    "collections.abc.Reversible": "3.6",
    "collections.abc.Collection": "3.6",
    "collections.abc.Buffer": "3.12",
    "collections.ChainMap": "3.3",
    "collections.OrderedDict": "3.1",
    # Replacements a fallback to a removed API exists for.
    "inspect.getfullargspec": "3.0",
    "inspect.signature": "3.3",
    "inspect.Signature": "3.3",
    "inspect.Parameter": "3.3",
    "base64.encodebytes": "3.1",
    "base64.decodebytes": "3.1",
    "math.gcd": "3.5",
    "shlex.quote": "3.3",
    "html.escape": "3.2",
    "html.unescape": "3.4",
    "importlib.import_module": "3.1",
    "importlib.reload": "3.4",
    "importlib.util.find_spec": "3.4",
    "importlib.util.spec_from_file_location": "3.4",
    "importlib.util.spec_from_loader": "3.4",
    "importlib.util.module_from_spec": "3.5",
    "importlib.machinery.SourceFileLoader": "3.3",
    "importlib.machinery.ModuleSpec": "3.4",
    "asyncio.run": "3.7",
    "asyncio.get_running_loop": "3.7",
    "asyncio.create_task": "3.7",
    "asyncio.current_task": "3.7",
    "asyncio.all_tasks": "3.7",
    "sys.getswitchinterval": "3.2",
    "sys.setswitchinterval": "3.2",
    "plistlib.load": "3.4",
    "plistlib.loads": "3.4",
    "plistlib.dump": "3.4",
    "plistlib.dumps": "3.4",
    "ast.Constant": "3.6",
    "ast.unparse": "3.9",
    "threading.get_ident": "3.3",
    "threading.get_native_id": "3.8",
    "unittest.IsolatedAsyncioTestCase": "3.8",
    "os.fspath": "3.6",
    "os.PathLike": "3.6",
    "os.scandir": "3.5",
    "pathlib.Path": "3.4",
    "pathlib.PurePath": "3.4",
    "shutil.which": "3.3",
    "shutil.get_terminal_size": "3.3",
    "shutil.disk_usage": "3.3",
    "subprocess.run": "3.5",
    "subprocess.DEVNULL": "3.3",
    "tempfile.TemporaryDirectory": "3.2",
    "textwrap.indent": "3.3",
    "textwrap.shorten": "3.4",
    "types.SimpleNamespace": "3.3",
    "types.MappingProxyType": "3.3",
    "types.GenericAlias": "3.9",
    "types.UnionType": "3.10",
    "types.NoneType": "3.10",
    "time.monotonic": "3.3",
    "time.perf_counter": "3.3",
    "time.perf_counter_ns": "3.7",
    "queue.SimpleQueue": "3.7",
    "statistics.fmean": "3.8",
    "math.prod": "3.8",
    "math.isqrt": "3.8",
    "math.dist": "3.8",
    "math.lcm": "3.9",
    "itertools.pairwise": "3.10",
    "itertools.batched": "3.12",
    "functools.lru_cache": "3.2",
    "functools.singledispatch": "3.4",
    "functools.singledispatchmethod": "3.8",
    "functools.cached_property": "3.8",
    "functools.cache": "3.9",
    "contextlib.nullcontext": "3.7",
    "contextlib.AsyncExitStack": "3.7",
    "contextlib.asynccontextmanager": "3.7",
    "contextlib.aclosing": "3.10",
    "contextlib.chdir": "3.11",
    "dataclasses.dataclass": "3.7",
    "dataclasses.field": "3.7",
    "dataclasses.KW_ONLY": "3.10",
    "enum.Enum": "3.4",
    "enum.IntEnum": "3.4",
    "enum.Flag": "3.6",
    "enum.IntFlag": "3.6",
    "enum.auto": "3.6",
    "enum.StrEnum": "3.11",
    "datetime.UTC": "3.11",
    "zoneinfo.ZoneInfo": "3.9",
    # Version-gated typing additions projects guard with an except ImportError.
    **dict.fromkeys(
        (
            "typing.Literal",
            "typing.Final",
            "typing.Protocol",
            "typing.TypedDict",
            "typing.SupportsIndex",
            "typing.get_origin",
            "typing.get_args",
            "typing.final",
            "typing.runtime_checkable",
        ),
        "3.8",
    ),
    "typing.Annotated": "3.9",
    **dict.fromkeys(
        (
            "typing.ParamSpec",
            "typing.TypeAlias",
            "typing.Concatenate",
            "typing.TypeGuard",
            "typing.is_typeddict",
        ),
        "3.10",
    ),
    **dict.fromkeys(
        (
            "typing.Self",
            "typing.Never",
            "typing.LiteralString",
            "typing.TypeVarTuple",
            "typing.Unpack",
            "typing.assert_never",
            "typing.assert_type",
            "typing.reveal_type",
            "typing.dataclass_transform",
            "typing.Required",
            "typing.NotRequired",
            "typing.get_overloads",
        ),
        "3.11",
    ),
    "typing.override": "3.12",
    "typing.TypeAliasType": "3.12",
    **dict.fromkeys(
        (
            "typing.TypeIs",
            "typing.ReadOnly",
            "typing.NoDefault",
            "typing.get_protocol_members",
            "typing.is_protocol",
        ),
        "3.13",
    ),
}

KNOWN_IMPORTS: Final[Mapping[str, PythonMinor]] = MappingProxyType(
    {
        name: PythonMinor.parse(since)
        for name, since in {**_MODULES, **_LATER_MODULES, **_ATTRIBUTES}.items()
    }
)
